# Generated by Django 4.2.24 on 2025-10-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_category_product_delete_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='product',
            name='block',
            field=models.CharField(blank=True, help_text='Block or wing (e.g., A Block, North Wing)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='location_details',
            field=models.CharField(blank=True, help_text='Additional location details', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='room_number',
            field=models.CharField(blank=True, help_text='Room number (e.g., 205, A101)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('books', 'Books'), ('electronics', 'Electronics'), ('furniture', 'Furniture'), ('clothing', 'Clothing'), ('accessories', 'Accessories'), ('sports', 'Sports'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='floor',
            field=models.CharField(choices=[('ground', 'Ground Floor'), ('first', 'First Floor'), ('second', 'Second Floor'), ('third', 'Third Floor')], max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='location',
            field=models.CharField(choices=[('bh1-front', 'BH1 Front'), ('bh1-back', 'BH1 Back'), ('gh1-front', 'GH1 Front'), ('gh1-back', 'GH1 Back'), ('gh2-front', 'GH2 Front'), ('gh2-back', 'GH2 Back'), ('old-campus', 'Old Campus')], max_length=20),
        ),
    ]
