# Generated by Django 4.2.24 on 2025-10-15 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_product_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='academic_year',
            field=models.CharField(blank=True, choices=[('p1', 'P1'), ('p2', 'P2'), ('e1', 'E1'), ('e2', 'E2'), ('e3', 'E3'), ('e4', 'E4')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='additional_contact',
            field=models.TextField(blank=True, help_text='Additional contact information', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair')], default='good', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='negotiable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('books', 'Books'), ('furniture', 'Furniture'), ('clothing', 'Clothing'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='location',
            field=models.CharField(choices=[('bh1-front', 'BH1 Front'), ('bh1-back', 'BH1 Back'), ('bh2-front', 'BH2 Front'), ('bh2-back', 'BH2 Back'), ('gh1-front', 'GH1 Front'), ('gh1-back', 'GH1 Back'), ('gh2-front', 'GH2 Front'), ('gh2-back', 'GH2 Back'), ('old-campus', 'Old Campus')], max_length=20),
        ),
    ]
