# Generated by Django 4.2.24 on 2025-10-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_delete_category_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='block',
            new_name='wing',
        ),
        migrations.RemoveField(
            model_name='product',
            name='additional_contact',
        ),
        migrations.RemoveField(
            model_name='product',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='product',
            name='location_details',
        ),
        migrations.AddField(
            model_name='product',
            name='academic_year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
